[versions]
micronaut = "4.10.14"
micronaut-docs = "3.0.0"
micronaut-test = "4.6.2"
micronaut-graphql = "4.8.0"
micronaut-gradle-plugin = "4.6.2"

groovy = "4.0.24"
spock = "2.3-groovy-4.0"

apollo = "3.8.2"
jetbrains-annotations = "24.0.1"

managed-graphql-java-extended-scalars = "20.2"

[libraries]
# Core
micronaut-core = { module = "io.micronaut:micronaut-core-bom", version.ref = "micronaut" }

managed-graphql-java-extended-scalars = { module = "com.graphql-java:graphql-java-extended-scalars", version.ref = "managed-graphql-java-extended-scalars" }

# BOMs
micronaut-graphql = { module = "io.micronaut.graphql:micronaut-graphql-bom", version.ref = "micronaut-graphql" }

apollo-runtime = { module = "com.apollographql.apollo3:apollo-runtime", version.ref = "apollo" }
apollo-rx3-support = { module = "com.apollographql.apollo3:apollo-rx3-support", version.ref = "apollo" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }

# plugins
micronaut-gradle-plugin = { module = "io.micronaut.gradle:micronaut-gradle-plugin", version.ref = "micronaut-gradle-plugin" }
